spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/db01
    username: postgres
    password: #abc123#
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
    show-sql: false

server:
  port: 8080
